<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.johnymuffin.beta</groupId>
    <artifactId>discordranksyncer</artifactId>
    <version>1.2.0</version>
    <name>DiscordRankSyncer</name>
    <description>A plugin to sync JohnyPerms groups to Discord roles.</description>

    <properties>
        <maven.compiler.release>25</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <repositories>
        <repository>
            <id>legacyminecraft-nexus</id>
            <url>https://repository.legacyminecraft.com/repository/maven-public/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.15.0</version>
                <configuration>
                    <release>${maven.compiler.release}</release>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>

        <dependency>
            <groupId>com.legacyminecraft</groupId>
            <artifactId>poseidon-api</artifactId>
            <version>2.0.0</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.retromc.discordcore.v6</groupId>
            <artifactId>DiscordCore-6</artifactId>
            <version>1.0.0</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.johnymuffin.beta</groupId>
            <artifactId>discordauth</artifactId>
            <version>1.2.0</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.retromc</groupId>
            <artifactId>RetroBridge</artifactId>
            <version>1.1.1</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>net.dv8tion</groupId>
            <artifactId>JDA</artifactId>
            <version>6.6.0</version>
            <scope>provided</scope>
        </dependency>

    </dependencies>
</project>
