name: DiscordRankSyncer
main: com.johnymuffin.beta.DiscordRankSyncer.DiscordRankSyncer
author: JohnyMuffin
version: ${project.version}
depend:
  - RetroBridge
  - DiscordCore
  - DiscordAuthentication
